### ISSUE TITLE
[REQ] Support for resetting rank

### ISSUE THREAD

**Issue by crashzk** [ABKAM2023/CS2-RanksPoints#3]
I believe it would be interesting to add the option for the administrator to choose how he will reset the players.

Something like:
- `!resetrank "SteamID64"` - Removes statistics from your games;
   - `all`- Will reset all data;
   - `exp` - Will reset data on experience points; **_(value, rank)_**
   - `stats` - Will reset statistics data; **_(kills, deaths, shoots, hits, headshots, assists, round_win, round_lose, statistics)_**
   - `playtime` - Will reset playtime data;

In other words, one option to reset all information, another to reset just the rank points, another to remove all statistics and another to remove playtime

I believe it would be interesting to even add a command to completely delete all data from the target player, some command like `!deleterank "SteamID64"`. In the case of admin access and when using it in a player, delete everything and delete it from the database.

And also add the `!resetmyrank` command so that players themselves can reset their rank and points only. This command would be interesting to add an option to leave enabled or not for players, many server owners may want to disable this feature for all players.

**Comment by ABKAM2023** [comment]
In the next update, I'm thinking of adding these commands.
