### ISSUE TITLE
[REQ] Support for rank images on the scoreboard

### ISSUE THREAD

**Issue by crashzk** [ABKAM2023/CS2-RanksPoints#4]
Implement players' rankings to be displayed on the scoreboard based on their points.

![image](https://github.com/ABKAM2023/CS2-RanksPoints/assets/32937653/54137bd1-e93a-46a3-955f-c01b66e28648)
![image](https://github.com/ABKAM2023/CS2-RanksPoints/assets/32937653/8cafc3bc-bbf7-4c3a-b836-231f60858088)
![image](https://github.com/ABKAM2023/CS2-RanksPoints/assets/32937653/0360a70a-2678-434c-b2ab-f36897411b66)

Each rank has its points configured in the plugin configuration, it would be interesting for each rank that the player reaches to show the rank he is in on the score.

To begin with, we can use the patents that are in CS2, Competitive and PREMIER and Wingman, and thus allow us to configure which patent image it will show as default.

In the future, if CS2 allows the use of FastDL, we can start creating our own patent images and using them.

**Comment by crashzk** [comment]
Path of the `.svg` images of the patents in the CS2 VPK file `pak01_dir.vpk`.

```
...csgo\panorama\images\icons\skillgroups
```

**Comment by ABKAM2023** [comment]
At the moment, I'm not sure how to implement this in CS2, but I will try

**Comment by crashzk** [comment]
> At the moment, I'm not sure how to implement this in CS2, but I will try

Doubt, would it be possible with this plugin now?

https://github.com/KillStr3aK/ResourcePrecacher

Or I misunderstood how it works.
